
FROM node:lts-buster

WORKDIR /myapp

COPY package*.json ./

RUN npm install

COPY . .

ENV REACT_APP_API_HOST games-store-back
ENV REACT_APP_API_PORT 3001

EXPOSE 3000

ENTRYPOINT ["./docker-front-container-set-back-ip.sh"]
